### ISSUE TITLE
best.hyperbolic

### ISSUE THREAD

**Issue by wallmichael** [derrickturk/aRpsDCA#5] opened 2016-11-03 19:52 UTC
When fitting type curves with the best.hyperbolic function 30% of the time the results are clearly not the correct fit. When this happens the b value is always only 2 significant digits.  If the upper and lower constraints are changed it will eventually return the correct fit.  Any idea why the model is doing this and also why when it doesn't find a solution it acts as if it has.  

Thanks,
Mike

**Comment by derrickturk** [comment] 2016-11-04 20:50
@wallmichael could you post some example data that reproduces the issue? Thanks!

**Comment by wallmichael** [comment] 2016-11-07 18:45
I am not sure the best way to provide data over this website. I can show you an image if this works: 
![gasfit](https://cloud.githubusercontent.com/assets/23245976/20070893/3a2cb0d4-a4f0-11e6-8c61-56510bdb9509.png)

Otherwise maybe i can create some type of smaller fake data-set that mimics the problem i am having.

**Comment by derrickturk** [comment] 2016-11-08 03:59
If you have a file with the data, you can attach it to a comment here; it'd also be good to see the exact code you are using to fit. As a shot in the dark, this could also be a unit conversion issue. The default bounds are tuned for use with "yearly" units. Also, is this with the latest version installed from github or the slightly older version (1.1.0) currently on CRAN? A few defaults have been tweaked to handle daily data better but I haven't pushed a new version to CRAN yet.

**Comment by wallmichael** [comment] 2016-11-08 19:21
I am using the version from CRAN.  I tried to get the one from github but had an issue when i tried to follow the instructions you gave here. 

I have attached the code and the data from one of the wells that does not work.  you will see that by changing the bounds it fits the curve one way but not the other.  I am unable to come up with a consistent set of boundary conditions that will fit all of the wells.  

Thanks,
Mike


[testwell.zip](https://github.com/derrickturk/aRpsDCA/files/579146/testwell.zip)

**Comment by derrickturk** [comment] 2016-11-08 19:37
Thanks! Ok, this looks like instantaneous rate and cumulative production data from late in the life of a well. The Arps declines can be fit to either instantaneous rate vs. time or cumulative production vs. time; trying to fit rate vs. cumulative (as in the example code) isn't supported in aRpsDCA although I suppose with some algebra it'd be possible. Trying to fit to rate vs cumulative would suffer from the problem that this choice of variables tends to "compress" the data and minimize the apparent distinction between "good" and "bad" fits (you'll hear reservoir engineers talk about "non-unique fits"). It'd also likely be better to fit data going back to "time zero" or at least to the well's peak initial production.

**Comment by wallmichael** [comment] 2016-11-08 19:45
I have split the data up to fit 1 curve to the beginning of the data and 1 curve to the end of the data.  This happens to be the second curve for this particular well but the fit problem occurs just as often with the first curve as the second one.  Also, it is not rate vs cum it is pressure normalized rate vs cum.  First my code calculated BHFP and then it normalized all the gas rates.  

Would it do a better job of fitting if i simply multiplied the pressure normalized rate by 1000 to make the errors seem larger?

Thanks,
Mike

**Comment by derrickturk** [comment] 2016-11-08 19:57
I don't think aRpsDCA is a good fit for the process you are describing. It's really intended for a pretty conventional DCA workflow of fitting single Arps decline curves to rate-vs-time or cumulative-vs-time data for a well's entire producing history. If the goal is just to forecast well production, I'd recommend trying a fit (with best.*) of rate vs time or, if that seems too noisy, of cumulative vs. time (with best.*.from.Np). 

Otherwise, it sounds like you are in the territory of material balance or rate-transient analysis.

**Comment by wallmichael** [comment] 2016-11-08 20:36
I am pretty happy with the results of my model other than the fact that some of the time the aRpsDCA provides an answer that doesn't fit the data.  

We are trying to assign an NPV or discounted EUR for each well assuming that they were brought online at a fixed line pressure.  By fitting a hyperbolic curve to the pressure normalized gas rate vs cum we have been able to do that.  This allows us to compare different completions regardless of the flowing conditions when the well is turned in line.  

That being said if aRpsDCA only works 70% of the time I will have to use a different curve fitting code.  Previously I was simply using lm.fit to fit exponential curves but it was under estimating the EUR and it was biased toward wells with longer production histories.  The hyperbolic fit from your software solved this problem.  

Thanks for the help. I appreciate your responsiveness. aRpsDCA is a very nice bit of code.  I am sure I will be able to find a work around or aonther way to fit curves to my data.

**Comment by derrickturk** [comment] 2016-11-10 19:33
That's definitely an off-label use of the Arps curve. If you're getting good results as measured by reliable forecasting against new data, I suppose that's viable, but I'd encourage you to look into some more established methodologies for well decline forecasting.

In any case this is outside the scope of what aRpsDCA is intended to do, so I am closing this issue.

**Closed by derrickturk** 2016-11-10 19:33 UTC
Labels: invalid
